### ISSUE TITLE
EntHitSkip / EntHitOnly

### ISSUE THREAD

**Issue by Fasteroid** [dvdvideo1234/ControlSystemsE2#1]
the EntHitSkip and EntHitOnly functions don't appear to do anything—am I doing something wrong or is this a bug?

```
@name Test
@inputs 
@outputs [H1 H2 H3]:array C
@persist [A B]:ftrace E:entity
@trigger 
@model models/sprops/cuboids/height06/size_1/cube_6x6x6.mdl
runOnTick(1)

if(first() || dupefinished())
{
    holoCreate(1)
    E = entity()
    A = E:setFTrace(vec(0,0,0),vec(0,0,1), -25):addEntHitSkip(entity()) #ignore the chip ent?
}

A:smpLocal()
holoPos(1,A:getHitPos())
```
(when this is spawned, the holo is always stuck in the e2)

**Comment by dvdvideo1234** [comment]
It is weird that it does that, I will check it out.

**Comment by dvdvideo1234** [comment]
@Fasteroid

Hello,
In this case, you are creating a tracer from the center of the cube pointing local down with 25 units of length ( notice the `vec(0,0,1)` and the length of `-25`  ) as you sample it locally ( relative to the `E = entity()` added via  `addEntHitSkip` ). The documentation states that the [direction goes reversed if the length is negated](https://github.com/dvdvideo1234/ControlSystemsE2/wiki/FTrace#how-to-create-an-instance-then). This should result in the tracer hutting the ground when it is spawned and the `HitPos` is sandwiched between the ground and the `E2` model.

Do you experience something different ?

**Comment by dvdvideo1234** [comment]
The `Only` functions are intended when you need to hit one single related parameter like single entity, class, model, or something else persisting in the given list. For example, you can filter only hitting the world entity using `addHitOnly("IsWorld", 1)`

**Comment by dvdvideo1234** [comment]
@Fasteroid,

After some testing I see what the issue is really now ;) Thanks for sharing... [Fixed](https://github.com/dvdvideo1234/ControlSystemsE2/commit/44bcd7a27aff4e451b4a86deb0e75a64f50b2132) !
